version: '2.0'

services:
  db:
    image: postgres:9.6.1
    ports:
          - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booktrackr

