version: '2'
services:
    database:
      image: "postgres:9.4"
      ports:
        - "5433:5433"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: booktrackrTestDb