ALTER TABLE book
  ADD COLUMN created TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE book
  ADD COLUMN modified TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE book
  ADD COLUMN version INTEGER NOT NULL DEFAULT 0;
